# Generated by Django 3.0.8 on 2020-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=254)),
                ('logo', models.CharField(max_length=254)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
